# Q1 :

In [10]:
import numpy as np
a= np.array([5,9,2,0,1,7,7,4])
print("original array",a)
print("array to list")
print(a.tolist())

original array [5 9 2 0 1 7 7 4]
array to list
[5, 9, 2, 0, 1, 7, 7, 4]


# Q2:

In [22]:
import numpy as np
ar= np.array([[0,1,2],[3,4,5],[6,7,8]])
print(ar)
sum=a+b+c
a=ar[0][0]
b=ar[1][1]
c=ar[2][2]
print(sum)
a=ar[2][0]
b=ar[1][1]
c=ar[0][2]
sum2=a+b+c
print(sum2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12
12


# Q3 :

In [45]:
import numpy as np
a= np.array([[1,2],[3,5]])
list=[]
x=2
if x<a[0][0]:
    list.append(a[0][0])
if x<a[0][1]:
    list.append(a[0][1])
if x<a[1][0]:
    list.append(a[1][0])
if x<a[1][1]:
    list.append(a[1][1])
print(list)


[3, 5]


# Q4 :

In [24]:
import numpy as np
A=np.array([7,8,9,3])
B=np.array([5,2,1,4])
C=A+B
print(C)

[12 10 10  7]


# Q5 :

In [35]:
import numpy as np
ar=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(ar)
m=(ar[0][0]+ar[0][1]+ar[0][2])/len(ar)
print(m)
m=(ar[1][0]+ar[1][1]+ar[1][2])/len(ar)
print(m)
m=(ar[2][0]+ar[2][1]+ar[2][2])/len(ar)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1.0
4.0
7.0
